[package]
name = "byteorder-lite"
version = "0.1.0"
description = "Library for reading/writing numbers in big-endian and little-endian."
documentation = "https://docs.rs/byteorder-lite"
homepage = "https://github.com/image-rs/byteorder-lite"
repository = "https://github.com/image-rs/byteorder-lite"
readme = "README.md"
categories = ["encoding", "parsing", "no-std"]
keywords = ["byte", "endian", "big-endian", "little-endian", "binary"]
license = "Unlicense OR MIT"
edition = "2021"
rust-version = "1.60"
include = ["README.md", "LICENSE-MIT", "UNLICENSE", "src/*"]

[lib]
bench = false

[dev-dependencies]
quickcheck = { version = "0.9.2", default-features = false }
rand = "0.7"

[features]
default = ["std"]
std = []

[profile.bench]
opt-level = 3
